-- <auto-generated>
--   This code was generated by a tool.
--   Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
-- </auto-generated>


/*
 * TABLE: TenantStore.DBSERVER
 *
 * */

-- USE <database-name>
-- GO

-- DROP TABLE [TenantStore].[DBSERVER]
-- GO

CREATE TABLE [TenantStore].[DBSERVER] (
      [ID] VARCHAR(50) NOT NULL
    , [NAME] NVARCHAR(128) NOT NULL
    , [BKUPUSERNAME] VARCHAR(MAX) NOT NULL
    , [MNGRUSERNAME] VARCHAR(MAX) NOT NULL
    , [MNGRUSERPASS] VARCHAR(MAX) NOT NULL
    , CONSTRAINT [PK_DBSERVER] PRIMARY KEY NONCLUSTERED ( [ID] )
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_DBSERVER_1] ON [TenantStore].[DBSERVER] (
    [NAME]
)
GO

-- Tpl: DbSql-CreateTable-1.0.tt
-- Src: DatabaseServer.tbl
