-- <auto-generated>
--   This code was generated by a tool.
--   Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
-- </auto-generated>


/*
 * TABLE: TenantStore.MAILSERVER
 *
 * */

-- USE <database-name>
-- GO

-- DROP TABLE [TenantStore].[MAILSERVER]
-- GO

CREATE TABLE [TenantStore].[MAILSERVER] (
      [ID] VARCHAR(50) NOT NULL
    , [NAME] NVARCHAR(128) NOT NULL
    , [FROM_ADDR] NVARCHAR(256) NOT NULL
    , [FROM_NAME] NVARCHAR(50) NOT NULL
    , [PORT] INT NOT NULL CONSTRAINT [DF_MAILSERVER_PORT] DEFAULT ( 0 )
    , [REQUIRES_SSL] TINYINT NOT NULL CONSTRAINT [DF_MAILSERVER_SSL_OFF] DEFAULT ( 0 )
    , [USE_AUTH] TINYINT NOT NULL CONSTRAINT [DF_MAILSERVER_AUTH_OFF] DEFAULT ( 0 )
    , [USERNAME] VARCHAR(MAX) NULL
    , [USERPASS] VARCHAR(MAX) NULL
    , CONSTRAINT [PK_MAILSERVER] PRIMARY KEY NONCLUSTERED ( [ID] )
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_MAILSERVER_1] ON [TenantStore].[MAILSERVER] (
    [NAME]
)
GO

-- Tpl: DbSql-CreateTable-1.0.tt
-- Src: MailServer.tbl
