-- <auto-generated>
--   This code was generated by a tool.
--   Changes to this file may cause incorrect behaviour and will be lost if the code is regenerated.
-- </auto-generated>


/*
 * TABLE: dbo.T_PROPERTY_BAG
 *
 * */

-- USE <database-name>
-- GO

-- DROP TABLE [dbo].[T_PROPERTY_BAG]
-- GO

CREATE TABLE [dbo].[T_PROPERTY_BAG] (
      [TENANT_ID] INT NOT NULL
    , [BAG_KEY] VARCHAR(50) NOT NULL
    , [PROPERTY_NAME] VARCHAR(128) NOT NULL
    , [PROPERTY_VALUE] NVARCHAR(1024) NULL
    , CONSTRAINT [PK_PROPERTY_BAG] PRIMARY KEY NONCLUSTERED ( [TENANT_ID], [BAG_KEY], [PROPERTY_NAME] )
)
GO

CREATE NONCLUSTERED INDEX [IX_PROPERTY_BAG_1] ON [dbo].[PROPERTY_BAG] (
    [TENANT_ID], [BAG_KEY]
)
GO

-- Tpl: DbSql-CreateTable-1.0.tt
-- Src: PropertyBagItem.tbl
